//! Integration tests for generated-file classification (issue #348).
//!
//! Exercises `Backend::commit_generated_flags`, which reads each file's blob
//! head at a commit, reads `.gitattributes` (`linguist-generated` / `-diff`),
//! and combines them via the pure `kagi_domain::generated` classifier (the
//! attribute wins). Builds a small repo with the `git` CLI in a temp dir.

use std::path::Path;
use std::process::Command;

use tempfile::TempDir;

use kagi_git::{commit_log, Backend, CommitId, FileStatus};

fn git(dir: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(dir)
        .env("GIT_AUTHOR_NAME", "Test")
        .env("GIT_AUTHOR_EMAIL", "test@example.com")
        .env("GIT_COMMITTER_NAME", "Test")
        .env("GIT_COMMITTER_EMAIL", "test@example.com")
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .env("HOME", dir)
        .status()
        .expect("git command failed to start");
    assert!(
        status.success(),
        "git {} exited with {:?}",
        args.join(" "),
        status.code()
    );
}

fn write_file(dir: &Path, name: &str, content: &str) {
    let path = dir.join(name);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).unwrap();
    }
    std::fs::write(path, content).expect("write_file failed");
}

fn init(tmp: &TempDir) -> &Path {
    let dir = tmp.path();
    git(dir, &["init", "-b", "main", "."]);
    git(dir, &["config", "user.name", "Test"]);
    git(dir, &["config", "user.email", "test@example.com"]);
    git(dir, &["config", "commit.gpgsign", "false"]);
    dir
}

fn head_id(backend: &Backend) -> CommitId {
    let repo = git2::Repository::open(backend.path()).expect("reopen for log");
    let commits = commit_log(&repo, 1).expect("commit_log failed");
    commits.into_iter().next().expect("no commits").id
}

/// Return the `is_generated` flag for `path` in the HEAD commit.
fn flag_for(backend: &Backend, id: &CommitId, files: &[FileStatus], path: &str) -> bool {
    let idx = files
        .iter()
        .position(|f| f.path.to_string_lossy() == path)
        .unwrap_or_else(|| panic!("{path} not in changed files"));
    backend.commit_generated_flags(id, files)[idx]
}

#[test]
fn content_and_filename_rules_classify_generated() {
    let tmp = TempDir::new().unwrap();
    let dir = init(&tmp);

    write_file(
        dir,
        "src/main.rs",
        "fn main() {\n    println!(\"hi\");\n}\n",
    );
    write_file(dir, "Cargo.lock", "# generated by cargo\n[[package]]\n");
    let long = "a".repeat(200);
    write_file(dir, "bundle.js", &format!("{long}\n{long}\n"));
    write_file(
        dir,
        "api/foo.pb.go",
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
    );

    git(dir, &["add", "."]);
    git(dir, &["commit", "-m", "add files"]);

    let backend = Backend::open(dir).unwrap();
    let id = head_id(&backend);
    let files = backend.commit_changed_files(&id).unwrap();

    assert!(!flag_for(&backend, &id, &files, "src/main.rs"));
    assert!(flag_for(&backend, &id, &files, "Cargo.lock"));
    assert!(flag_for(&backend, &id, &files, "bundle.js"));
    assert!(flag_for(&backend, &id, &files, "api/foo.pb.go"));
}

#[test]
fn gitattributes_linguist_generated_forces_generated() {
    let tmp = TempDir::new().unwrap();
    let dir = init(&tmp);

    // A perfectly normal source file, but marked generated via .gitattributes.
    write_file(dir, "vendor.py", "def f():\n    return 1\n");
    write_file(dir, ".gitattributes", "vendor.py linguist-generated=true\n");
    git(dir, &["add", "."]);
    git(dir, &["commit", "-m", "add vendored"]);

    let backend = Backend::open(dir).unwrap();
    let id = head_id(&backend);
    let files = backend.commit_changed_files(&id).unwrap();

    assert!(
        flag_for(&backend, &id, &files, "vendor.py"),
        "linguist-generated attribute must force generated"
    );
}

#[test]
fn gitattributes_linguist_generated_false_overrides_content() {
    let tmp = TempDir::new().unwrap();
    let dir = init(&tmp);

    // Content says generated (Cargo.lock), attribute says NOT — attribute wins.
    write_file(dir, "Cargo.lock", "# lock\n");
    write_file(
        dir,
        ".gitattributes",
        "Cargo.lock linguist-generated=false\n",
    );
    git(dir, &["add", "."]);
    git(dir, &["commit", "-m", "add lock with override"]);

    let backend = Backend::open(dir).unwrap();
    let id = head_id(&backend);
    let files = backend.commit_changed_files(&id).unwrap();

    assert!(
        !flag_for(&backend, &id, &files, "Cargo.lock"),
        "linguist-generated=false must override the filename rule"
    );
}

#[test]
fn gitattributes_minus_diff_folds() {
    let tmp = TempDir::new().unwrap();
    let dir = init(&tmp);

    // `-diff` (diff unset) → fold as generated, even for normal content.
    write_file(dir, "secret.txt", "plain content\n");
    write_file(dir, ".gitattributes", "secret.txt -diff\n");
    git(dir, &["add", "."]);
    git(dir, &["commit", "-m", "add nodiff file"]);

    let backend = Backend::open(dir).unwrap();
    let id = head_id(&backend);
    let files = backend.commit_changed_files(&id).unwrap();

    assert!(
        flag_for(&backend, &id, &files, "secret.txt"),
        "-diff attribute must fold (classify as generated)"
    );
}
