//! Unit tests for the Commit Panel fold logic (#348 generated / #338 agent
//! artifacts / #411 conflicted-file exemption). Split out of commit_panel.rs
//! to keep that file under the LOC ratchet.

use super::*;

/// Build an empty state (no repo) so `rebuild_derived` can be exercised
/// in isolation.
fn empty_state() -> CommitPanelState {
    CommitPanelState {
        unstaged: Vec::new(),
        staged: Vec::new(),
        unstaged_stats: Vec::new(),
        staged_stats: Vec::new(),
        conflicted_paths: std::collections::HashSet::new(),
        selected_file: None,
        commit_msg: String::new(),
        plan_modal: None,
        tree_view: false,
        unstaged_tree: Vec::new(),
        staged_tree: Vec::new(),
        unstaged_stat_index: std::collections::HashMap::new(),
        staged_stat_index: std::collections::HashMap::new(),
        unstaged_gen_files: Vec::new(),
        unstaged_normal_files: Vec::new(),
        staged_gen_files: Vec::new(),
        staged_normal_files: Vec::new(),
        generated_expanded: false,
        unstaged_artifact_files: Vec::new(),
        staged_artifact_files: Vec::new(),
        agent_expanded: false,
    }
}

fn modified(path: &str) -> FileStatus {
    FileStatus {
        path: PathBuf::from(path),
        change: ChangeKind::Modified,
    }
}

/// issue #348: rebuild splits generated files out of the flat/tree lists and
/// the fold defaults collapsed (only the header row shows until expanded).
#[test]
fn rebuild_folds_generated_files() {
    let mut s = empty_state();
    // Matches the reported bug: Cargo.lock + main.rs unstaged.
    s.unstaged = vec![modified("Cargo.lock"), modified("src/main.rs")];
    // Cargo.lock (index 0) is generated; main.rs (index 1) is not.
    s.rebuild_derived(&[true, false], &[]);

    assert_eq!(s.unstaged_gen_files, vec![0]);
    assert_eq!(s.unstaged_normal_files, vec![1]);
    // Pruned tree (flat has 1 dir-less file 'main.rs'): no Cargo.lock row.
    assert!(s.unstaged_tree.iter().all(|r| !matches!(
        r,
        kagi_ui_core::file_tree::TreeRow::File { file_index: 0, .. }
    )));

    // Collapsed by default → 1 extra row (the header only).
    assert!(!s.generated_expanded);
    assert_eq!(s.generated_extra_rows(false), 1);
    // Expanded → header + the 1 generated file.
    s.generated_expanded = true;
    assert_eq!(s.generated_extra_rows(false), 2);
}

/// No generated files → no fold, no extra rows.
#[test]
fn no_generated_no_fold() {
    let mut s = empty_state();
    s.unstaged = vec![modified("src/a.rs"), modified("src/b.rs")];
    s.rebuild_derived(&[false, false], &[]);
    assert!(s.unstaged_gen_files.is_empty());
    assert_eq!(s.unstaged_normal_files, vec![0, 1]);
    assert_eq!(s.generated_extra_rows(false), 0);
}

/// issue #338: ArtifactConfig files fold under a collapsed "Agent artifacts"
/// group; a convention body (CLAUDE.md) stays in the main list; and the
/// artifact axis takes precedence over the generated fold.
#[test]
fn rebuild_folds_agent_artifacts() {
    let mut s = empty_state();
    s.unstaged = vec![
        modified("src/main.rs"),           // 0: normal
        modified(".claude/settings.json"), // 1: artifact
        modified("CLAUDE.md"),             // 2: convention body (inline, badged)
        modified(".mcp.json"),             // 3: artifact
    ];
    // .claude/settings.json (index 1) is ALSO flagged generated by #348 →
    // artifact precedence must keep it in the artifact fold, out of the
    // generated group.
    s.rebuild_derived(&[false, true, false, false], &[]);

    assert_eq!(s.unstaged_artifact_files, vec![1, 3]);
    // Convention body + normal remain in the main list (not folded).
    assert_eq!(s.unstaged_normal_files, vec![0, 2]);
    // Generated group must NOT contain the artifact even though it was
    // flagged generated (artifact precedence).
    assert!(s.unstaged_gen_files.is_empty());

    // Collapsed by default → 1 extra row (header only).
    assert!(!s.agent_expanded);
    assert_eq!(s.agent_extra_rows(false), 1);
    s.agent_expanded = true;
    assert_eq!(s.agent_extra_rows(false), 3); // header + 2 files
}

/// issue #411: a conflicted file classified as generated (e.g. a Cargo.lock
/// merge conflict) must NEVER be folded into the collapsed "Generated (N)"
/// group — an unresolved conflict has to stay a visible normal row.
/// Mutation: drop the `us_conf` mask in `rebuild_derived` and Cargo.lock
/// lands in `unstaged_gen_files`, failing the assertions below.
#[test]
fn conflicted_generated_file_is_not_folded() {
    let mut s = empty_state();
    s.unstaged = vec![modified("Cargo.lock"), modified("src/main.rs")];
    // Cargo.lock (index 0) is BOTH generated AND conflicted.
    s.conflicted_paths.insert(PathBuf::from("Cargo.lock"));
    s.rebuild_derived(&[true, false], &[]);

    // Conflict wins: not folded as generated, stays a normal visible row.
    assert!(
        s.unstaged_gen_files.is_empty(),
        "conflicted file must not be folded as generated"
    );
    assert_eq!(s.unstaged_normal_files, vec![0, 1]);
    assert_eq!(s.generated_extra_rows(false), 0);
    // The conflicted file must appear as a row in the (unpruned) tree.
    assert!(s.unstaged_tree.iter().any(|r| matches!(
        r,
        kagi_ui_core::file_tree::TreeRow::File { file_index: 0, .. }
    )));
}

/// issue #411: a conflicted file that is ALSO an agent artifact must not be
/// folded into the "Agent artifacts" group either — the conflict axis wins
/// over both folds.
#[test]
fn conflicted_artifact_file_is_not_folded() {
    let mut s = empty_state();
    s.unstaged = vec![modified(".mcp.json"), modified("src/main.rs")];
    s.conflicted_paths.insert(PathBuf::from(".mcp.json"));
    s.rebuild_derived(&[false, false], &[]);

    assert!(
        s.unstaged_artifact_files.is_empty(),
        "conflicted file must not be folded as an agent artifact"
    );
    assert_eq!(s.unstaged_normal_files, vec![0, 1]);
}
