//! Generated / lockfile classification — pure, no I/O (issue #348).
//!
//! Ports the subset of GitHub Linguist's `generated.rb` locked by the PM:
//! a filename table (lockfiles), Go `Code generated` headers, protobuf output,
//! minified `.js`/`.css` (average line length), and source-map tails. The
//! caller passes the file's path and the first ~8 KiB of its bytes (`head`);
//! that head is enough for the first-40-lines / average-line-length checks.
//!
//! Truncation caveat: the source-map check looks at the **last two lines of
//! `head`**. If the real file is larger than the slice passed in, its trailing
//! `sourceMappingURL` line is in the part we never saw, so a >8 KiB minified
//! bundle whose only generated signal is that tail may be missed. Lockfiles,
//! Go, protobuf, and minified detection do not depend on the tail.
//!
//! `.gitattributes` (`linguist-generated` / `-diff`) is read in the git layer
//! (needs a repo) and passed here as [`classify_generated`]'s `attr_override`.

/// Basenames Linguist treats as generated regardless of content (lockfiles).
///
/// Exact basename match, case-sensitive — a file merely *named* `foo.lock`
/// that is not in this table stays non-generated unless another rule fires,
/// matching Linguist.
const LOCKFILE_NAMES: &[&str] = &[
    "Cargo.lock",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "bun.lock",
    "bun.lockb",
    "flake.lock",
    "pixi.lock",
    "Gemfile.lock",
    "poetry.lock",
    "composer.lock",
    "Podfile.lock",
    "packages.lock.json",
    "deno.lock",
    "go.sum",
];

/// The final path component (basename) of `path`, split on `/`.
fn basename(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path)
}

/// Lowercased file extension including the leading dot (e.g. `.js`), or `""`.
fn ext_lower(path: &str) -> String {
    let name = basename(path);
    match name.rsplit_once('.') {
        Some((_, e)) if !e.is_empty() => format!(".{}", e.to_ascii_lowercase()),
        _ => String::new(),
    }
}

/// Decode `head` as lossy UTF-8 and return its lines.
fn head_lines(head: &[u8]) -> Vec<String> {
    String::from_utf8_lossy(head)
        .lines()
        .map(|l| l.to_string())
        .collect()
}

/// Linguist filename table — a lockfile basename.
fn is_lockfile_name(path: &str) -> bool {
    LOCKFILE_NAMES.contains(&basename(path))
}

/// Go `// Code generated ... DO NOT EDIT.` header in the first 40 lines of a
/// `.go` file (Linguist `generated_go?`).
fn is_generated_go(path: &str, lines: &[String]) -> bool {
    if ext_lower(path) != ".go" {
        return false;
    }
    lines
        .iter()
        .take(40)
        .any(|l| l.starts_with("// Code generated ") && l.trim_end().ends_with(" DO NOT EDIT."))
}

/// protobuf compiler banner in the first 3 lines (Linguist
/// `generated_protocol_buffer?`). The double space in the marker is verbatim
/// from protoc's output.
fn is_generated_protobuf(lines: &[String]) -> bool {
    // ponytail: no extension gate — the banner is unique enough that any file
    // carrying it verbatim is protoc output. Linguist also gates on extension;
    // dropping the gate only ever adds a file that truly is generated.
    lines
        .iter()
        .take(3)
        .any(|l| l.contains("Generated by the protocol buffer compiler.  DO NOT EDIT!"))
}

/// Minified `.js` / `.css`: average line length > 110 (Linguist
/// `generated_minified_files?`).
fn is_minified(path: &str, lines: &[String]) -> bool {
    let ext = ext_lower(path);
    if ext != ".js" && ext != ".css" {
        return false;
    }
    if lines.is_empty() {
        return false;
    }
    let total: usize = lines.iter().map(|l| l.chars().count()).sum();
    (total as f64 / lines.len() as f64) > 110.0
}

/// `sourceMappingURL` in the last two lines of the (possibly truncated) head.
fn has_source_map_tail(lines: &[String]) -> bool {
    let start = lines.len().saturating_sub(2);
    lines[start..]
        .iter()
        .any(|l| l.contains("sourceMappingURL"))
}

/// Classify a file as generated from its path and the first ~8 KiB of content.
///
/// Ports Linguist's locked rule subset. Returns `true` when any rule fires.
/// A normal source file, and a `*.lock` file not in [`LOCKFILE_NAMES`], stay
/// `false` unless another rule fires — matching Linguist.
pub fn is_generated(path: &str, head: &[u8]) -> bool {
    if is_lockfile_name(path) {
        return true;
    }
    let lines = head_lines(head);
    is_generated_go(path, &lines)
        || is_generated_protobuf(&lines)
        || is_minified(path, &lines)
        || has_source_map_tail(&lines)
}

/// Combine the content classifier with a `.gitattributes` override.
///
/// `attr_override` is resolved in the git layer from `.gitattributes`:
/// * `Some(true)`  — `linguist-generated` set, or `-diff` (fold): force generated.
/// * `Some(false)` — `linguist-generated` explicitly unset/false: force NOT generated.
/// * `None`        — no attribute; fall back to [`is_generated`].
///
/// The attribute always wins over content, per the issue.
pub fn classify_generated(path: &str, head: &[u8], attr_override: Option<bool>) -> bool {
    match attr_override {
        Some(v) => v,
        None => is_generated(path, head),
    }
}

/// How generated files are grouped for the diff file list (issue #348).
///
/// `generated` / `normal` hold indices into the caller's file slice, in
/// original order. `collapsed` is the section's default fold state — **true**
/// (folding default-on): generated files start hidden under a "Generated (N)"
/// disclosure the user can expand.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedGroup {
    /// Indices of files classified generated (shown under the collapsed group).
    pub generated: Vec<usize>,
    /// Indices of the remaining (normal) files.
    pub normal: Vec<usize>,
    /// Default fold state of the generated section — `true` (collapsed).
    pub collapsed: bool,
}

/// Partition file indices into normal + generated groups from a per-file
/// `is_generated` flag slice. The generated section defaults to collapsed.
pub fn group_generated(flags: &[bool]) -> GeneratedGroup {
    let mut generated = Vec::new();
    let mut normal = Vec::new();
    for (i, &g) in flags.iter().enumerate() {
        if g {
            generated.push(i);
        } else {
            normal.push(i);
        }
    }
    GeneratedGroup {
        generated,
        normal,
        collapsed: true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Filename table (lockfiles) ──────────────────────────────────
    #[test]
    fn lockfile_names_are_generated() {
        for name in LOCKFILE_NAMES {
            assert!(is_generated(name, b""), "{name} should be generated");
            let nested = format!("some/dir/{name}");
            assert!(is_generated(&nested, b""), "{nested} should be generated");
        }
    }

    #[test]
    fn cargo_lock_and_package_lock_specifically() {
        assert!(is_generated("Cargo.lock", b""));
        assert!(is_generated("package-lock.json", b""));
        assert!(is_generated("pnpm-lock.yaml", b""));
    }

    // ── NEGATIVE: a *.lock not in the table stays non-generated ──────
    #[test]
    fn unknown_lock_file_is_not_generated() {
        assert!(!is_generated("mystuff.lock", b"key = value\n"));
        assert!(!is_generated("config.lock", b"a\nb\nc\n"));
    }

    // ── NEGATIVE: normal source files are not misclassified ──────────
    #[test]
    fn normal_source_files_not_generated() {
        assert!(!is_generated(
            "src/main.rs",
            b"fn main() {\n    println!(\"hi\");\n}\n"
        ));
        assert!(!is_generated(
            "app/index.js",
            b"function greet(name) {\n  return `hi ${name}`;\n}\n"
        ));
        assert!(!is_generated(
            "styles/site.css",
            b".btn {\n  color: red;\n}\n"
        ));
        assert!(!is_generated(
            "pkg/thing.go",
            b"package pkg\n\nfunc Do() {}\n"
        ));
    }

    // ── Go ──────────────────────────────────────────────────────────
    #[test]
    fn go_code_generated_header() {
        let src = b"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n";
        assert!(is_generated("api/foo.pb.go", src));
    }

    #[test]
    fn go_header_only_within_first_40_lines() {
        let mut src = String::new();
        for _ in 0..45 {
            src.push_str("// filler\n");
        }
        src.push_str("// Code generated by tool. DO NOT EDIT.\n");
        assert!(!is_generated("x.go", src.as_bytes()));
    }

    #[test]
    fn go_header_requires_go_extension() {
        let src = b"// Code generated by tool. DO NOT EDIT.\n";
        assert!(!is_generated("notes.txt", src));
    }

    // ── protobuf ────────────────────────────────────────────────────
    #[test]
    fn protobuf_banner() {
        let src =
            b"// Generated by the protocol buffer compiler.  DO NOT EDIT!\n// source: x.proto\n";
        assert!(is_generated("x.pb.go", src));
        assert!(is_generated("x.pb.cc", src));
    }

    #[test]
    fn protobuf_banner_must_be_in_first_three_lines() {
        let src = b"a\nb\nc\n// Generated by the protocol buffer compiler.  DO NOT EDIT!\n";
        assert!(!is_generated("x.cc", src));
    }

    // ── minified (avg line length > 110) ────────────────────────────
    #[test]
    fn minified_js_by_average_line_length() {
        let long_line = "a".repeat(200);
        let src = format!("{long_line}\n{long_line}\n");
        assert!(is_generated("bundle.js", src.as_bytes()));
    }

    #[test]
    fn minified_css_by_average_line_length() {
        let long_line = "x".repeat(200);
        assert!(is_generated("app.css", long_line.as_bytes()));
    }

    #[test]
    fn short_lined_js_not_minified() {
        let src = "var a = 1;\nvar b = 2;\nvar c = 3;\n";
        assert!(!is_generated("app.js", src.as_bytes()));
    }

    /// MUTATION GUARD (§6): the `> 110` boundary. Average exactly 110 must be
    /// NOT generated; 111 must be generated. Reverting/loosening the rule (e.g.
    /// `>= 110`, or dropping the check) flips one of these.
    #[test]
    fn minified_boundary_is_strictly_greater_than_110() {
        let l110 = "a".repeat(110);
        assert!(
            !is_generated("edge.js", l110.as_bytes()),
            "avg == 110 must NOT be minified"
        );
        let l111 = "a".repeat(111);
        assert!(
            is_generated("edge.js", l111.as_bytes()),
            "avg == 111 must be minified"
        );
    }

    #[test]
    fn minified_only_for_js_css() {
        let long_line = "a".repeat(200);
        assert!(!is_generated("big.rs", long_line.as_bytes()));
        assert!(!is_generated("big.md", long_line.as_bytes()));
    }

    // ── source-map tail ─────────────────────────────────────────────
    #[test]
    fn source_map_url_in_last_two_lines() {
        let src = b"console.log(1)\n//# sourceMappingURL=app.js.map\n";
        assert!(is_generated("app.js", src));
    }

    #[test]
    fn source_map_url_not_in_tail_is_ignored() {
        let mut src = String::from("//# sourceMappingURL=a.map\n");
        for _ in 0..10 {
            src.push_str("code();\n");
        }
        assert!(!is_generated("app.js", src.as_bytes()));
    }

    // ── attribute override precedence ───────────────────────────────
    /// MUTATION GUARD (§6): the attribute override. `Some(false)` must force a
    /// lockfile to NOT generated (attribute wins over content); `Some(true)`
    /// must force a normal file to generated. Reverting the override (always
    /// deferring to `is_generated`) flips both.
    #[test]
    fn attribute_override_wins_over_content() {
        assert!(!classify_generated("Cargo.lock", b"", Some(false)));
        assert!(classify_generated(
            "src/main.rs",
            b"fn main() {}\n",
            Some(true)
        ));
        assert!(classify_generated("Cargo.lock", b"", None));
        assert!(!classify_generated("src/main.rs", b"fn main() {}\n", None));
    }

    // ── grouping helper (folding default-on) ────────────────────────
    /// §6: folding default-on — the grouping helper puts generated files in the
    /// generated group and defaults the section to collapsed.
    #[test]
    fn group_generated_defaults_collapsed() {
        let g = group_generated(&[false, true, false, true]);
        assert_eq!(g.normal, vec![0, 2]);
        assert_eq!(g.generated, vec![1, 3]);
        assert!(g.collapsed, "generated section must default collapsed");
    }

    #[test]
    fn group_generated_all_normal() {
        let g = group_generated(&[false, false]);
        assert_eq!(g.generated, Vec::<usize>::new());
        assert_eq!(g.normal, vec![0, 1]);
    }
}
