#!/usr/bin/env bash
# Generate a Homebrew formula for Kagi from the release's bare-binary archives
# (ADR-0120). Reads the per-leg `SHA256SUMS-*.txt` produced by `release.yml`,
# pulls the SHA-256 of each `kagi-<version>-<triple>.tar.gz`, and emits a
# `kagi.rb` formula installing the `kagi` binary.
#
# Usage:
#   scripts/gen_homebrew_formula.sh <version> <dist-dir> <out-file>
#
# The result is shipped as a release asset, so `brew install` against
#   https://github.com/TomiXRM/kagi/releases/latest/download/kagi.rb
# always installs the latest published version. It is also drop-in ready for a
# `homebrew-kagi` tap.
set -euo pipefail

VERSION="${1:?usage: gen_homebrew_formula.sh <version> <dist-dir> <out-file>}"
DIST_DIR="${2:?missing <dist-dir>}"
OUT="${3:?missing <out-file>}"

REPO="https://github.com/TomiXRM/kagi"
DL="${REPO}/releases/download/v${VERSION}"

# Look up the SHA-256 for an asset filename across all SHA256SUMS-*.txt files.
# Returns empty string if the asset is absent (e.g. a build leg was skipped).
sha_for() {
  local name="$1"
  # shasum/sha256sum format: "<hex>  <filename>". Match the exact basename.
  awk -v n="$name" '$2 == n { print $1; exit }' "${DIST_DIR}"/SHA256SUMS-*.txt 2>/dev/null || true
}

mac_arm="kagi-${VERSION}-aarch64-apple-darwin.tar.gz"
lin_x86="kagi-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
lin_arm="kagi-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"

sha_mac_arm="$(sha_for "$mac_arm")"
sha_lin_x86="$(sha_for "$lin_x86")"
sha_lin_arm="$(sha_for "$lin_arm")"

# macOS arm64 and linux x86_64 are the baseline targets — fail loudly if either
# is missing so a broken release does not silently ship an unusable formula.
[ -n "$sha_mac_arm" ] || { echo "missing checksum for $mac_arm" >&2; exit 1; }
[ -n "$sha_lin_x86" ] || { echo "missing checksum for $lin_x86" >&2; exit 1; }

{
  cat <<RUBY
# Generated by scripts/gen_homebrew_formula.sh — do not edit by hand.
class Kagi < Formula
  desc "Safety-first, commit-graph Git GUI built with GPUI"
  homepage "${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${DL}/${mac_arm}"
      sha256 "${sha_mac_arm}"
    end
    on_intel do
      odie "Kagi has no Intel macOS build yet — build from source: ${REPO}"
    end
  end

  on_linux do
    on_intel do
      url "${DL}/${lin_x86}"
      sha256 "${sha_lin_x86}"
    end
RUBY

  if [ -n "$sha_lin_arm" ]; then
    cat <<RUBY
    on_arm do
      url "${DL}/${lin_arm}"
      sha256 "${sha_lin_arm}"
    end
RUBY
  else
    cat <<RUBY
    on_arm do
      odie "Kagi arm64 Linux build is unavailable for this release — build from source: ${REPO}"
    end
RUBY
  fi

  cat <<RUBY
  end

  def install
    bin.install "kagi"
  end

  test do
    assert_match "kagi #{version}", shell_output("#{bin}/kagi --version")
  end
end
RUBY
} > "$OUT"

echo "wrote $OUT (version ${VERSION})"
